### ISSUE TITLE
Can it be used to handle other types of data?

### ISSUE THREAD

**Issue by ShuaiNIEgithub** [wangshisheng/NAguideR#1]
Can NAguideR be used to process other types of data? For example, RNAseq gene expression matrix, metabolome matrix, etc.

**Comment by wangshisheng** [comment]
Yes, the classic criteria can be used for RNAseq gene expression matrix, metabolome matrix, etc. So you can stop there. And the proteomic criteria are only for the proteomics matrix.

**Comment by ShuaiNIEgithub** [comment]
Great tool! 
Thank you.
