### ISSUE TITLE
disconnect from server error => many times today

### ISSUE THREAD

**Issue by ihorrible** [wangshisheng/NAguideR#2]
Hi everyone ! 

I cannot generate classic and proteomic criteria for my data. as well as download the dataset with imputed values. 
I always see the same error "disconnected from the server and reload". I have 5000 rows and 24 columns in my dataset. 

It seems like it is too big to be processed on your website. I also tried to do it locally with run in R, but I also have an issue with dream AI package (https://github.com/WangLab-MSSM/DreamAI/issues/11)

![Снимок](https://user-images.githubusercontent.com/63013549/155324495-fa389878-bc04-4be5-a345-a3285d305274.PNG)

**Comment by wangshisheng** [comment]
Hi ihorrible,

    Yes, it indeed seems that it is too big to be processed on this website. Please try this link: https://www.omicsolution.com/wukong/NAguideR.

    For installation of this package, I think your Rtools were not installed right, please reinstall it and choose "Full installation to build 32 or 64 bit" in the following promp: https://stackoverflow.com/questions/39090983/rcpp-rtools-installed-but-error-message-g-not-found
![image](https://user-images.githubusercontent.com/19953005/155439672-cbdfaaef-e89d-49b3-8d64-c64fd6ae68b1.png)

**Comment by wangshisheng** [comment]
> Hi ihorrible,
> 
> ```
> Yes, it indeed seems that it is too big to be processed on this website. Please try this link: https://www.omicsolution.com/wukong/NAguideR.
> 
> For installation of this package, I think your Rtools were not installed right, please reinstall it and choose "Full installation to build 32 or 64 bit" in the following promp: https://stackoverflow.com/questions/39090983/rcpp-rtools-installed-but-error-message-g-not-found
> ```
> 
> ![image](https://user-images.githubusercontent.com/19953005/155439672-cbdfaaef-e89d-49b3-8d64-c64fd6ae68b1.png)

Please note: The Rtools version is still 4.0 as your R is >4.0. The picture above is just an example.

**Comment by ihorrible** [comment]
re-installation of rtools helps !!!! now everything works perfectly. although I have another issue with saving results with imputed values, but I will open a new issue
