### ISSUE TITLE
cannot save results with imputed values => column names are not defined

### ISSUE THREAD

**Issue by ihorrible** [wangshisheng/NAguideR#3]
Hi everyone! I get an error when  I tick "Customize the proteomic criteria or not?" at step 4 " Results and assessments": 

Translated from Russian => Warning: Error in h: error in evaluating the 'x' argument when selecting the method for the 'as.matrix' function: unspecified columns selected

  128: stop
  127: [.data.frame
  124: <reactive:accpprank4out> [C:\Users\iataraskin\Documents\R\win-library\4.1\NAguideR\NAguideRapp/app.R#2548]
  108: accpprank4out
  105: exprFunc [C:\Users\iataraskin\Documents\R\win-library\4.1\NAguideR\NAguideRapp/app.R#3136]
  104: widgetFunc
  103: ::
htmlwidgets
shinyRenderWidget
  102: func
   89: renderFunc
   88: renderFunc
   84: renderFunc
   83: output$accpprank4
    2: shiny::runApp
    1: NAguideR_app

But if I tick "Customize the classic criteria or not?' there is no error. 

I don't really understand how the selection of classic or proteomic criteria affects the results ? E.g. if for classic criteria the best method is impseqrob and for proteomic criteria the best method is bpca then can I choose bpca in 1.1 Select one method and tick classic criteria in 2.1? 

![1](https://user-images.githubusercontent.com/63013549/155456321-da3bf72a-92a9-4711-94d5-0cd3dcb8ad15.PNG)
![2](https://user-images.githubusercontent.com/63013549/155456323-01772715-263b-4933-82d2-56cfd67c6af9.PNG)
![3](https://user-images.githubusercontent.com/63013549/155456324-b143ef00-32f6-4a77-9a58-cd5278427893.PNG)

**Comment by wangshisheng** [comment]
Hi ihorrible,

What is the species of your data? Please note, NAguideR mainly supports Human data for the proteomic criteria.

Actually, you can choose any one criteria for your data, as they evaluate the results from different respects. Please read our paper and the supplementary notes: https://doi.org/10.1093/nar/gkaa498.


Shisheng

**Comment by ihorrible** [comment]
Hi ! I have a human data. If I select one criteria it will also lead to another error ...
