### ISSUE TITLE
final check is not OK, error: missing value where TRUE/FALSE needed

### ISSUE THREAD

**Issue by ihorrible** [wangshisheng/NAguideR#4]
Hi, everyone ! I use a local installation of NAguiderR and I have never seen this type of error before: missing value where TRUE/FALSE needed. There is nothing unusual in this human data. All preliminary check were fine:

![Снимок](https://user-images.githubusercontent.com/63013549/163719349-adcf08a0-250a-42f6-bf5e-bc5c8e91f740.PNG)
![imput data check](https://user-images.githubusercontent.com/63013549/163719384-9f5dcfa0-482f-4443-b332-a62fae3bafec.PNG)
[NAplot_bycolumn_1650204928.51691_after_removal426&8.pdf](https://github.com/wangshisheng/NAguideR/files/8501833/NAplot_bycolumn_1650204928.51691_after_removal426.8.pdf)

**Comment by ihorrible** [comment]
Should I ignore this error? As missing values I have an empty cells. May be I should add zero instead of empty cells? 

Warning: Error in if: missing value where TRUE/FALSE needed
  98: renderUI [C:\Users\iataraskin\Documents\R\win-library\4.1\NAguideR\NAguideRapp/app.R#3429]
  97: func
  84: renderFunc
  83: output$finalcheck2
   2: shiny::runApp
   1: NAguideR_app

**Comment by ihorrible** [comment]
It seems to me that problem is related with the following: 
![Uploading Снимок.PNG…]()

**Comment by wangshisheng** [comment]
Hi. I think one of the proteomic criteria is NaN, so NAguideR cannot decide what the exact value. You can just ignore this error and do not take those criteria with missing values into consideration or just add 0 instead as you mentioned. I will update these codes later.

Shisheng
