### ISSUE TITLE
Error in cor: 'x' is empty  

### ISSUE THREAD

**Issue by Maithy15** [wangshisheng/NAguideR#5]
Hi,

I used protein level data and evaluated the imputation by classic criteria but could not see the final results as it complained that X is empty. Should I always use peptide-level data to avoid this error? Also, DIA-NN reports modifications in peptide level data in Unimod format like "AAADEWTTC(UniMod:4)TPPSGLQGK". Does NAguideR recognize it? 

Also, will any imputation methods work even if all the values in one group are missing?

Thanks
Maithy

**Comment by wangshisheng** [comment]
Hi Maithy,

I am wondering whether you prepare your data format right, which means, you should prepare your data format as described in the supplementary notes. NAguideR can recognize the modification type from DIA-NN.

Well, for those values in one group are missing, you can use the minimum values instead.

If the error still exists, you can send your data to me by email and I will help to check it.


Bests,
Shisheng
