### ISSUE TITLE
 error: "infinite or missing values in 'x'

### ISSUE THREAD

**Issue by Zmged** [wangshisheng/NAguideR#6]
Hi,

I use data on a protein level and after classic criteria are calculated I get an error: "infinite or missing values in 'x'" and no results for PSS and no figures. I loaded the data as instructed in the manual, where for the first column I selected type "other" because instead of protein IDs, I'm using gene names. Do you know how I can fix this error?

**Comment by wangshisheng** [comment]
Hi,

that is complicated and I guess you did not prepare your data well, could you send your data (the Expression data and the Samples information data) to me? I will check it for you and try it. Your data is safe here. My email: wssdandan2009@outlook.com.


Bests
