### ISSUE TITLE
NAguideR在线网站证书到期

### ISSUE THREAD

**Issue by yangxinzhi** [wangshisheng/NAguideR#7]
![image](https://github.com/wangshisheng/NAguideR/assets/125720871/2e87ae57-ba55-4bec-9609-507c2b809a27)
我今天使用这个网站的时候发现他已经不能正常记载示例数据了，麻烦您维护一下？ 另外这是一个非常不错的工具

**Comment by wangshisheng** [comment]
你好，感谢支持，请用这个网址：https://www.omicsolution.com/wukong/NAguideR/
